export const ActionTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  CHANGE_THEME: 'CHANGE_THEME',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  SELECT_LANGUAGE: 'SELECT_LANGUAGE',
  PRODUCT_LIST: 'PRODUCT_LIST',
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  USER_LIST: 'USER_LIST',
  SET_USER_LIST: 'SET_USER_LIST',

  // POKEMON
  FETCH_POKEMON: 'FETCH_POKEMON',
  SET_FETCH_POKEMON: 'SET_FETCH_POKEMON',
  
  FETCH_POKEMON_REQUEST: 'FETCH_POKEMON_REQUEST',
  FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
  FETCH_POKEMON_FAILURE: 'FETCH_POKEMON_FAILURE',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
};
